version: "3.9"
services:
  db:
    image: mongo:4.2.11-bionic
    ports:
      - 8000:27017
    volumes:
      - employee-demo:/data/db
  backend:
    build: ./employee
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      MONGO_URL: mongodb://db:27017
  frontent:
    build: ./employee-ui
    ports:
      - 4200:4200
    depends_on:
      - backend
volumes:
  employee-demo: